=begin
Simple emlpoyee contract tracker api

This API allows management of client contracts and tracks history of employee contract assignments 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'DELETE', '/clients/{clientId}', controller_name: 'default', action_name: 'clients_client_id_delete'
  add_openapi_route 'GET', '/clients/{clientId}', controller_name: 'default', action_name: 'clients_client_id_get'
  add_openapi_route 'PUT', '/clients/{clientId}', controller_name: 'default', action_name: 'clients_client_id_put'
  add_openapi_route 'GET', '/clients', controller_name: 'default', action_name: 'clients_get'
  add_openapi_route 'POST', '/clients', controller_name: 'default', action_name: 'clients_post'
  add_openapi_route 'DELETE', '/contracts/{contractId}', controller_name: 'default', action_name: 'contracts_contract_id_delete'
  add_openapi_route 'GET', '/contracts/{contractId}', controller_name: 'default', action_name: 'contracts_contract_id_get'
  add_openapi_route 'PUT', '/contracts/{contractId}', controller_name: 'default', action_name: 'contracts_contract_id_put'
  add_openapi_route 'GET', '/contracts', controller_name: 'default', action_name: 'contracts_get'
  add_openapi_route 'POST', '/contracts', controller_name: 'default', action_name: 'contracts_post'
  add_openapi_route 'DELETE', '/employees/{employeeId}', controller_name: 'default', action_name: 'employees_employee_id_delete'
  add_openapi_route 'GET', '/employees/{employeeId}', controller_name: 'default', action_name: 'employees_employee_id_get'
  add_openapi_route 'PUT', '/employees/{employeeId}', controller_name: 'default', action_name: 'employees_employee_id_put'
  add_openapi_route 'GET', '/employees', controller_name: 'default', action_name: 'employees_get'
  add_openapi_route 'POST', '/employees', controller_name: 'default', action_name: 'employees_post'
  add_openapi_route 'GET', '/history', controller_name: 'default', action_name: 'history_get'
  add_openapi_route 'DELETE', '/history/{historyId}', controller_name: 'default', action_name: 'history_history_id_delete'
  add_openapi_route 'GET', '/history/{historyId}', controller_name: 'default', action_name: 'history_history_id_get'
  add_openapi_route 'PUT', '/history/{historyId}', controller_name: 'default', action_name: 'history_history_id_put'
  add_openapi_route 'POST', '/history', controller_name: 'default', action_name: 'history_post'
end
