=begin
Simple emlpoyee contract tracker api

This API allows management of client contracts and tracks history of employee contract assignments 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "client".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :url

      t.timestamps
    end

    create_table "_clients_get_request".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :url

      t.timestamps
    end

    create_table "contract".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :client_id
      t.string :type
      t.string :start_date
      t.string :end_date
      t.string :tech

      t.timestamps
    end

    create_table "contract_patch".pluralize.to_sym, id: false do |t|
      t.integer :client_id
      t.string :type
      t.string :start_date
      t.string :end_date
      t.string :tech

      t.timestamps
    end

    create_table "employee".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :github

      t.timestamps
    end

    create_table "_employees_get_request".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :github

      t.timestamps
    end

    create_table "history".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :client_id
      t.integer :contract_id
      t.integer :employee_id
      t.string :client_name
      t.string :employee_name
      t.string :role

      t.timestamps
    end

    create_table "history_patch".pluralize.to_sym, id: false do |t|
      t.integer :client_id
      t.integer :contract_id
      t.integer :employee_id
      t.string :role

      t.timestamps
    end

  end
end
