=begin
Simple emlpoyee contract tracker api

This API allows management of client contracts and tracks history of employee contract assignments 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def clients_client_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def clients_client_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def clients_client_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def clients_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def clients_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def contracts_contract_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def contracts_contract_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def contracts_contract_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def contracts_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def contracts_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def employees_employee_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def employees_employee_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def employees_employee_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def employees_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def employees_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_history_id_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_history_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_history_id_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def history_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
