=begin
Simple emlpoyee contract tracker api

This API allows management of client contracts and tracks history of employee contract assignments 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class EmployeesGetRequest < ApplicationRecord

end
